version: "3.9"
services:
  event-es-7:
    image: elasticsearch:7.17.10
    container_name: event-es-7
    ports:
      - 9200:9200
    environment:
      - cluster.name=event-es-7-cluster
      - node.name=event-es-7-node
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - es-data-7:/usr/share/elasticsearch/data
  event-es-kibana-7:
    image: kibana:7.17.10
    container_name: event-es-kibana-7
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://event-es-7:9200
    depends_on:
      - event-es-7
  event-es-8:
    image: elasticsearch:8.8.1
    container_name: event-es-8
    ports:
      - 9201:9200
    environment:
      - cluster.name=event-es-8-cluster
      - node.name=event-es-8-node
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - es-data-8:/usr/share/elasticsearch/data
  event-es-kibana-8:
    image: kibana:8.8.1
    container_name: event-es-kibana-8
    ports:
      - 5602:5601
    depends_on:
      - event-es-8
  event-os:
    image: opensearchproject/opensearch:2.8.0
    container_name: event-os
    ports:
      - 9202:9200
    environment:
      - cluster.name=event-os-cluster
      - node.name=event-os-node
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - os-data:/usr/share/elasticsearch/data
  event-os-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    container_name: event-os-dashboards
    ports:
      - 5603:5601
    environment:
      - OPENSEARCH_HOSTS=http://event-os:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - event-os
  event-es-6:
    image: elasticsearch:6.8.23
    container_name: event-es-6
    ports:
      - 9203:9200
    environment:
      - cluster.name=event-es-6-cluster
      - node.name=event-es-6-node
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - es-data-6:/usr/share/elasticsearch/data
  event-es-kibana-6:
    image: kibana:6.8.23
    container_name: event-es-kibana-6
    ports:
      - 5604:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://event-es-6:9200
    depends_on:
      - event-es-6
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:0.4.7
    container_name: zincsearch
    ports:
      - 4080:4080
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: Complexpass#123
  # doris:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfile-doris
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - "kafka-data:/bitnami"
  kafka-ui:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.4.3
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
    ports:
      - 9099:8080
    depends_on:
      - kafka
volumes:
  es-data-7:
  es-data-8:
  os-data:
  es-data-6:
  kafka-data:
